%{
    #include <iostream>
    #include <cstdlib>
    #include <string>
    #include <algorithm>

    #include "SymbolTable.hpp"
    
    extern int yylex();
    extern FILE *yyin;

    void yyerror(std::string poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }

    SymbolTable table;
%}

// unija
%union {
    std::string *s;
}

// tokeni
%token START
%token END
%token STRING
%token <s> ID
%token OUT
%token IN
%token ERR
%token SHL
%token SHR
%token <s> STRING_CONST
%token EQ
%token NEQ
%token PRINT
%token IF
%token ELSE

// asocijativnost
%nonassoc EQ NEQ
%left '+'
%left '*'
%right '~'
%nonassoc IF_NO_ELSE
%nonassoc ELSE

// type
%type <s> izraz
%type <s> uslov

// startni simbol
%start program

%%

program : START ':' niz_naredbi END     {}
;

niz_naredbi : niz_naredbi naredba
| naredba
;

naredba : STRING ID ';'     {
    bool retVal = table.VariableDefined(*$2);
    if (retVal == true)
        yyerror("Promenljiva vec definisana");
    table.DefineVariable(*$2, "");
}
| STRING ID '=' izraz ';'   {
    bool retVal = table.VariableDefined(*$2);
    if (retVal == true)
        yyerror("Promenljiva vec definisana");
    table.DefineVariable(*$2, *$4);
}
| OUT SHL izraz ';' {
    std::cout << (*$3) << std::endl;
}
| IN SHR ID ';'     {
    bool retVal = table.VariableDefined(*$3);
    if (retVal = false)
        yyerror("Promenljiva nije definisana");
    std::string s;
    std::cin >> s;
    table.UpdateVariable(*$3, s);
}
| ERR SHL izraz ';'     {
    std::cerr << (*$3) << std::endl;
}
| OUT SHL uslov ';'     {
    std::cout << (*$3) << std::endl;
}
| ID '=' izraz ';'      {
    bool retVal = table.UpdateVariable(*$1, *$3);
    if (retVal == false)
        yyerror("Promenljiva nije definisana");
    
}
| PRINT ';'     {
    std::cout << table << std::endl;
}
| IF '(' uslov ')' '{' niz_naredbi '}' ';' %prec IF_NO_ELSE
| IF '(' uslov ')' '{' niz_naredbi '}' ELSE '{' niz_naredbi '}' ';'
;

uslov : izraz EQ izraz      {
    if (*$1 == *$3) {
        $$ = new std::string("1");
    } else {
        $$ = new std::string("0");
    }
}
| izraz NEQ izraz       {
    if (*$1 != *$3) {
        $$ = new std::string("1");
    } else {
        $$ = new std::string("0");
    }
}
;


izraz : izraz '+' izraz     {
    $$ = new std::string(*$1 + *$3);
}
| izraz '*' izraz       {
    int i = 0;
    for (i = 0; i < std::min($1->size(), $3->size()); i++) {
        if ((*$1)[i] != (*$3)[i]) {
            break;
        }
    }
    if (i == 0)
        $$ = new std::string("");
    else
        $$ = new std::string($1->substr(0, i));
}
| '~' izraz     {
    std::reverse($2->begin(), $2->end());
    $$ = new std::string(*$2);
}
| '(' izraz ')'     {
    $$ = $2;
}
| ID    {
    bool retVal = table.VariableDefined(*$1);
    if (retVal == false)
        yyerror("Promenljiva nije definisana");
    $$ = new std::string(table.GetVariable(*$1));
}
| STRING_CONST  {
    $$ = new std::string($1->substr(1, $1->size() - 2));
}
;

%%

int main(int argc, char **argv) {

    if (argc != 2)
        yyerror("Nedostaje ulazni fajl!");

    yyin = fopen(argv[1], "r");
    if (yyin == NULL)
        yyerror("Otvaranje fajla nije uspelo!");

    if (yyparse() == 0) {
        std::cout << "Ispravna gramatika" << std::endl;
    } else {
        std::cout << "Neispravna gramatika" << std::endl;
    }

    fclose(yyin);

    exit(EXIT_SUCCESS);
}