%{
    #include <iostream>
    #include <cstdlib>
    #include <bitset>
    #include <map>
    
    extern int yylex();

    void yyerror(std::string poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }

    void print(char fmt, int br) {
        if (fmt == 'd') {
            std::cout << br << std::endl;
        } else if (fmt == 'h') {
            std::cout << std::hex << br << std::dec << std::endl;
        } else if (fmt == 'b') {
            std::cout << std::bitset<8*sizeof(int)>(br) << std::endl;
        } else {
            yyerror("Nepoznat format ispisa");
        }
    }

    std::map<std::string,int> promenljive;
%}

// unija
%union {
    char c;
    int d;
    std::string *s;
}

%token DEF
%token <s> ID
%token PRINT
%token <d> BROJ
%token <c> FMT
%token SHL
%token SHR
%token EQ
%token NEQ
%token LEQ
%token GEQ

// asocijativnost
%left '|'
%left '^'
%left '&'
%left SHL SHR
%left '+' '-'
%left '*' '/' '%'
%right '~'
%right UMINUS

%type <d> izraz logicka_naredba

%start program

%%

program : program naredba
| naredba
;

naredba : DEF ID ';'    {
    auto it = promenljive.find(*$2);
    if (it != promenljive.end()) {
        yyerror("Promenljiva vec definisana.");
    }
    promenljive[*$2] = 0;
}
| DEF ID '=' izraz ';'  {
    auto it = promenljive.find(*$2);
    if (it != promenljive.end()) {
        yyerror("Promenljiva vec definisana.");
    }
    promenljive[*$2] = $4;
}
| ID '=' izraz ';'      {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end()) {
        yyerror("Promenljiva nije definisana.");
    }
    it->second = $3;
}
| PRINT '(' '"' FMT '"' ',' izraz ')' ';'   {
    print($4, $7);
}
| logicka_naredba ';'   {
    std::cout << ($1 ? "true" : "false") << std::endl;
}
;

logicka_naredba : izraz EQ izraz    {
    $$ = $1 == $3;
}
| izraz NEQ izraz   {
    $$ = $1 != $3;
}
| izraz LEQ izraz   {
    $$ = $1 <= $3;
}
| izraz GEQ izraz   {
    $$ = $1 >= $3;
}
| izraz '<' izraz   {
    $$ = $1 < $3;
}
| izraz '>' izraz   {
    $$ = $1 > $3;
}
;

izraz : izraz '+' izraz     {
    $$ = $1 + $3;
}
| izraz '-' izraz       {
    $$ = $1 - $3;
}
| izraz '*' izraz       {
    $$ = $1 * $3;
}
| izraz '/' izraz       {
    if ($3 == 0)
        yyerror("Deljenje nulom.");
    $$ = $1 / $3;
}
| izraz '%' izraz       {
    if ($3 == 0)
        yyerror("Deljenje nulom.");
    $$ = $1 % $3;
}
| '(' izraz ')'     {
    $$ = $2;
}
| '-' izraz %prec UMINUS    {
    $$ = -$2;
}
| '~' izraz     {
    $$ = ~$2;
}
| izraz '&' izraz   {
    $$ = $1 & $3;
}
| izraz '|' izraz   {
    $$ = $1 | $3;
}
| izraz '^' izraz   {
    $$ = $1 ^ $3;
}
| izraz SHL izraz   {
    $$ = $1 >> $3;
}
| izraz SHR izraz   {
    $$ = $1 << $3;
}
| ID    {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end()) {
        yyerror("Promenljiva nije definisana");
    }
    $$ = it->second;
}
| BROJ  {
    $$ = $1;
}
;

%%

int main() {

    if (yyparse() == 0) {
        std::cout << "Ispravna gramatika" << std::endl;
    } else {
        std::cout << "Neispravna gramatika" << std::endl;
    }

    exit(EXIT_SUCCESS);
}