%{
    #include <iostream>
    #include <cstdlib>
    #include <string>
    #include <vector>
    #include <map>
    #include <cmath>

    extern int yylex();

    void yyerror(const std::string& poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }

    void ispisi(std::vector<int>* v1) {
        std::cout << "<";
        for (int i = 0; i < v1->size(); i++) {
            std::cout << (*v1)[i];
            if (i != v1->size() - 1)
                std::cout << ", ";
        }
        std::cout << ">" << std::endl;
    }

    std::vector<int>* saberi(std::vector<int>* v1, std::vector<int>* v2) {
        std::vector<int> novi(v1->size());
        for (int i = 0; i < novi.size(); i++) {
            novi[i] = ((*v1)[i] + (*v2)[i]);
        }
        return new std::vector<int>(novi);
    }

    std::vector<int>* oduzmi(std::vector<int>* v1, std::vector<int>* v2) {
        std::vector<int> novi(v1->size());
        for (int i = 0; i < novi.size(); i++) {
            novi[i] = ((*v1)[i] + (*v2)[i]);
        }
        return new std::vector<int>(novi);
    }

    std::vector<int>* pomnozi_skalarom(std::vector<int>* v1, int skalar) {
        std::vector<int>* novi = new std::vector<int>(*v1);
        for (int i = 0; i < v1->size(); i++) {
            (*novi)[i] *= skalar;
        }
        return novi;
    }

    int skalarni_proizvod(std::vector<int>* v1, std::vector<int>* v2) {
        int rezultat = 0;
        for (int i = 0; i < v1->size(); i++) {
            rezultat += (*v1)[i] * (*v2)[i];
        }
        return rezultat;
    }

    double norma(std::vector<int>* v1) {
        int skalarni = skalarni_proizvod(v1, v1);
        return std::sqrt(skalarni);
    }

    double ugao(std::vector<int>* v1, std::vector<int>* v2) {
        int skalarni = skalarni_proizvod(v1, v2);
        double norma_1 = norma(v1);
        double norma_2 = norma(v2);
        double kosinus = (skalarni * 1.0) / (norma_1 * norma_2);
        return std::acos(kosinus);
    }

    bool jednaki(std::vector<int>* v1, std::vector<int>* v2) {
        if (v1->size() != v2->size())
            return false;
        if (ugao(v1, v2) == 0)
            return true;
        else
            return false;
    }

    std::map<std::string, std::vector<int>*> promenljive;

%}

%union {
    int vrednost;
    std::string* ime;
    std::vector<int>* niz;
}

%token <ime> ID_T
%token DODELA_T
%token PRINT_T
%token <vrednost> BROJ_T
%token UGAO_T
%token EQV_T

%left '+' '-'
%left '*'

%type naredba
%type <niz> izraz
%type <niz> nabrajanje

%start program

%%

program: program naredba ';'        {}
| naredba ';'       {}
;

naredba: ID_T DODELA_T izraz        {
    auto it = promenljive.find(*$1);
    if (it != promenljive.end())
        delete it->second;
    promenljive[*$1] = $3;
    delete $1;
}
| PRINT_T '(' izraz ')'     {
    ispisi($3);
}
| '|' izraz '|'     {
    std::cout << norma($2) << std::endl;
    delete $2;
}
| izraz '.' izraz       {
    if ($1->size() != $3->size())
        yyerror("Greska u dimenzionalnosti vektora");
    std::cout << skalarni_proizvod($1, $3) << std::endl;
    delete $1;
    delete $3;
}
| UGAO_T '(' izraz ',' izraz ')'    {
    std::cout << ugao($3, $5) << std::endl;
}
| EQV_T '(' izraz ',' izraz ')'     {
    if (jednaki($3, $5))
        std::cout << "True" << std::endl;
    else
        std::cout << "False" << std::endl;
    delete $3;
    delete $5;
}
;

izraz: izraz '+' izraz      {
    if ($1->size() != $3->size())
        yyerror("Greska u dimenzionalnosti vektora");
    $$ = saberi($1, $3);
    delete $1;
    delete $3;
}
| izraz '-' izraz       {
    if ($1->size() != $3->size())
        yyerror("Greska u dimenzionalnosti vektora");
    $$ = oduzmi($1, $3);
    delete $1;
    delete $3;
}
| BROJ_T '*' izraz      {
    $$ = pomnozi_skalarom($3, $1);
}
| ID_T      {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end())
        yyerror("Promenljiva " + *$1 + " nije definisana");
    $$ = new std::vector<int>(*(it->second));
    delete $1;
}
| '<' nabrajanje '>'        {
    $$ = $2;
}
;

nabrajanje: nabrajanje ',' BROJ_T       {
    $$ = $1;
    $$->push_back($3);
}
| BROJ_T        {
    $$ = new std::vector<int>();
    $$->push_back($1);
}
;

%%

int main() {

    if (yyparse() == 0) {
        std::cout << "Ispravna gramatika" << std::endl;
    } else {
        std::cout << "Neispravna gramatika" << std::endl;
    }

    exit(EXIT_SUCCESS);
}