%{
    #include <iostream>
    #include <cstdlib>
    #include <string>
    #include <map>

    #include "Kompleksni.hpp"

    extern int yylex();

    void yyerror(const std::string& poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }

    std::map<std::string, Kompleksni> promenljive;
%}

%union {
    double vrednost;
    std::string *ime;
    Kompleksni *komp;
}

%token DEF_T
%token <ime> ID_T
%token PRINT_T
%token <vrednost> BROJ_T
%token DELETE_T
%token ARG_T
%token EQ_T
%token NEQ_T

%left '+' '-'
%left '*' '/'
%right UNARNI_MINUS '~'

%type <komp> izraz

%%

program: program naredba    {}
| naredba   {}
;

naredba: DEF_T ID_T ';'     {
    auto it = promenljive.find(*$2);
    if (it != promenljive.end())
        yyerror("Promenljiva " + *$2 + " je vec definisana!");
    promenljive[*$2] = Kompleksni(0, 0);
    delete $2;
}
| DEF_T ID_T '=' izraz ';'  {
    auto it = promenljive.find(*$2);
    if (it != promenljive.end())
        yyerror("Promenljiva " + *$2 + " je vec definisana!");
    promenljive[*$2] = *$4;
    delete $2;
    delete $4;
}
| ID_T '=' izraz ';'        {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end())
        yyerror("Promenljiva " + *$1 + " nije definisana!");
    promenljive[*$1] = *$3;
    delete $1;
    delete $3;
}
| PRINT_T '(' izraz ')' ';'     {
    $3->ispisi();
    delete $3;
}
| DELETE_T ID_T ';'     {
    auto it = promenljive.find(*$2);
    if (it == promenljive.end())
        yyerror("promenljiva " + *$2 + " nije definisana!");
    promenljive.erase(*$2);
    delete $2;
}
| izraz EQ_T izraz ';'      {
    std::cout << (*$1 == *$3 ? "True" : "False") << std::endl;
    delete $1;
    delete $3;
}
| izraz NEQ_T izraz ';'     {
    std::cout << (*$1 != *$3 ? "True" : "False") << std::endl;
    delete $1;
    delete $3;
}
;

izraz: BROJ_T   {
    $$ = new Kompleksni($1);
}
| ID_T      {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end())
        yyerror("Promenljiva " + *$1 + " nije definisana!");
    $$ = new Kompleksni(promenljive[*$1]);
    delete $1;
}
| '<' izraz ',' izraz '>'   {
    $$ = new Kompleksni($2->_re, $4->_re);
    delete $2;
    delete $4;
}
| '<' izraz '>'         {
    $$ = new Kompleksni($2->_re, 0);
    delete $2;
}
| '|' izraz '|'         {
    $$ = new Kompleksni($2->moduo());
    delete $2;
}
| ARG_T '(' izraz ')'   {
    $$ = new Kompleksni($3->argument());
    delete $3;
}
| izraz '+' izraz       {
    $$ = new Kompleksni(*$1 + *$3);
    delete $1;
    delete $3;
}
| izraz '-' izraz       {
    $$ = new Kompleksni(*$1 - *$3);
    delete $1;
    delete $3;
}
| izraz '*' izraz       {
    $$ = new Kompleksni(*$1 * *$3);
    delete $1;
    delete $3;
}
| izraz '/' izraz       {
    $$ = new Kompleksni(*$1 / *$3);
    delete $1;
    delete $3;
}
| '-' izraz %prec UNARNI_MINUS      {
    $$ = new Kompleksni(-(*$2));
    delete $2;
}
| '~' izraz         {
    $$ = new Kompleksni(~(*$2));
    delete $2;
}
| '(' izraz ')'     {
    $$ = $2;
}
;

%%

int main() {

    if (yyparse() == 0) {
        std::cout << "Ispravna gramatika" << std::endl;
    } else {
        std::cout << "Neispravna gramatika" << std::endl;
    }

    return 0;
}