%{
    #include <iostream>
    #include <cstdlib>
    #include <map>
    #include <vector>

    extern int yylex();

    void yyerror(const std::string& poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }

    std::map<std::string, std::vector<int>> promenljive;    
%}

%union {
    int broj;                 
    std::string *niska;         
    std::vector<int> *lista;    
}

%token LIST_T
%token <niska> ID_T
%token <broj> BROJ_T
%token PRINT_T
%token <niska> KOMENTAR_T
%token APPEND_T

%left '+'
%left '*'

%type <lista> izraz
%type <lista> nabrajanje

%start program

%%

program: program naredba    {}
| naredba   {}
;

naredba: LIST_T ID_T ';'        { 
    auto it = promenljive.find(*$2);
    if (it != promenljive.end())
        yyerror("Lista " + *$2 + " je vec deklarisana!");
    promenljive[*$2] = std::vector<int>();
    delete $2;
}
| LIST_T ID_T '=' izraz ';'     {
    auto it = promenljive.find(*$2);
    if (it != promenljive.end())
        yyerror("Lista " + *$2 + " je vec deklarisana!");
    promenljive[*$2] = *$4;
    delete $2;
    delete $4;
}
| ID_T '=' izraz ';'    {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end())
        yyerror("Lista " + *$1 + " nije deklarisana pre upotrebe!");
    promenljive[*$1] = *$3;
    delete $1;
    delete $3;
}
| PRINT_T '(' KOMENTAR_T ')' ';'    {
    std::string s = *$3;
    std::cout << s.substr(1, s.length() - 2) << std::endl;
    delete $3;
}
| PRINT_T '(' izraz ')' ';'     {
    std::cout << "[";
    for (int i = 0; i < $3->size(); i++) {
        std::cout << (*$3)[i];
        if (i != $3->size() - 1)
            std::cout << ", ";
    }
    std::cout << "]" << std::endl;
    delete $3;
}
| ID_T '.' APPEND_T '(' izraz ')' ';'   {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end())
        yyerror("Lista " + *$1 + " nije deklarisana!");
    std::vector<int>& l = promenljive[*$1];
    l.insert(l.end(), $5->begin(), $5->end());
    delete $1;
    delete $5;
}
;

izraz: '[' nabrajanje ']'       {
    $$ = $2;
}
| ID_T      {
    auto it = promenljive.find(*$1);
    if (it == promenljive.end())
        yyerror("Lista " + *$1 + " nije deklarisana!");
    $$ = new std::vector<int>(promenljive[*$1]);
    delete $1;
}  
| '[' ']'   {
    $$ = new std::vector<int>();
}
| izraz '+' izraz       {
    std::vector<int> *nova_lista = new std::vector<int>(*$1);
    nova_lista->insert(nova_lista->end(), $3->begin(), $3->end());
    $$ = nova_lista;
    delete $1;
    delete $3;
}
| izraz '*' BROJ_T      {
    std::vector<int> *nova_lista = new std::vector<int>();
    for (int i = 0; i < $3; i++) {
        for (int element : *$1) {
            nova_lista->push_back(element);
        }
    }
    $$ = nova_lista;
    delete $1;
}
| BROJ_T    {
    std::vector<int> *l = new std::vector<int>();
    l->push_back($1);
    $$ = l;
}
;

nabrajanje: nabrajanje ',' BROJ_T   {
    $1->push_back($3);
    $$ = $1;
}
| BROJ_T    {
    std::vector<int> *l = new std::vector<int>();
    l->push_back($1);
    $$ = l;
}
;

%%

int main() {

    if (yyparse() == 0) {
        std::cout << "Ispravna gramatika" << std::endl;
    } else {
        std::cout << "Nesipravna gramatika" << std::endl;
    }

    return 0;
}