%{
    #include <iostream>
    #include <cstdlib>
    #include <map>
    #include <vector>
    #include <string>
    
    extern int yylex();

    void yyerror(const std::string& poruka) {
        std::cerr << poruka << std::endl;
        exit(EXIT_FAILURE);
    }

    void stampaj(int broj, int osnova) {
        if (osnova == 10)
            printf("%d", broj);
        else if (osnova == 8)
            printf("%o", broj);
        else if (osnova == 16)
            printf("%x", broj);
        else
            yyerror("Nepodrzana osnova!");
        std::cout << std::endl;
    }

    void stampaj_listu(std::vector<int>* l) {
        std::cout << "[";
        for (unsigned i = 0; i < l->size(); i++) {
            std::cout << (*l)[i];
            if (i != l->size() - 1)
                std::cout << ", ";
        }
        std::cout << "]" << std::endl;
    }

    std::map<std::string, int> promenljive;
    std::map<std::string, std::vector<int>*> liste;
%}

%union {
    int broj;
    std::string *ime;
    std::vector<int>* elementi;
}

%token INT_T
%token <ime> ID_T
%token <broj> BROJ_T
%token PRINT_T
%token EQV_T
%token SHL_T
%token SHR_T
%token LIST_T
%token <ime> LID_T

%left '|'
%left '^'
%left '&'
%left SHL_T SHR_T
%left '+' '-'
%left '*' '/'
%right '~' UMINUS

%type <broj> izraz
%type <elementi> lista_izraz
%type <elementi> lista_vrednosti

%start program

%%

program: program naredba ';'    {}
| naredba ';'       {}
;

naredba: INT_T ID_T     {
    if (promenljive.find(*$2) != promenljive.end())
        yyerror("Promenljiva vec deklarisana!");
    promenljive[*$2] = 0;
    delete $2;
}
| INT_T ID_T '=' izraz      {
    if (promenljive.find(*$2) != promenljive.end())
        yyerror("Promenljiva vec deklarisana!");
    promenljive[*$2] = $4;
    delete $2;
}
| ID_T '=' izraz        {
    if (promenljive.find(*$1) == promenljive.end())
        yyerror("Promenljiva nije deklarisana!");
    promenljive[*$1] = $3;
    delete $1;
}
| PRINT_T '(' izraz ',' BROJ_T ')'      {
    if ($5 != 8 && $5 != 10 && $5 != 16)
        yyerror("Nepodrzana osnova!");
    stampaj($3, $5);
}
| PRINT_T '(' izraz ')'     {
    stampaj($3, 10);
}
| PRINT_T '(' lista_izraz ')'       {
    stampaj_listu($3);
}
| izraz EQV_T izraz     {
    if ($1 == $3)
        std::cout << "True!" << std::endl;
    else
        std::cout << "False!" << std::endl;
}
| LIST_T LID_T '=' lista_izraz      {
    if (liste.find(*$2) != liste.end())
        yyerror(*$2 + " vec deklarisana lista!");
    liste[*$2] = $4;
    delete $2;
}
;

izraz: izraz '+' izraz  {
    $$ = $1 + $3;
}
| izraz '-' izraz       {
    $$ = $1 - $3;
}
| izraz '*' izraz       {
    $$ = $1 * $3;
}
| izraz '/' izraz       {
    $$ = $1 / $3;
}
| izraz '&' izraz       {
    $$ = $1 & $3;
}
| izraz '|' izraz       {
    $$ = $1 | $3;
}
| izraz '^' izraz       {
    $$ = $1 ^ $3;
}
| '(' izraz ')'         {
    $$ = $2;
}
| izraz SHL_T izraz     {
    if ($3 <= 0)
        yyerror("Drugi operand mora biti veci od nule!");
    $$ = $1 << $3;
}
| izraz SHR_T izraz     {
    if ($3 <= 0)
        yyerror("Drugi operand mora biti veci od nule!");
    $$ = $1 >> $3;
}
| '~' izraz     {
    $$ = ~$2;
}
| '-' izraz %prec UMINUS        {
    $$ = -$2;
}
| BROJ_T        {
    $$ = $1;
}
| ID_T      {
    if (promenljive.find(*$1) == promenljive.end())
        yyerror(*$1 + " nije deklarisana promenljiva!");
    $$ = promenljive[*$1];
    delete $1;
}
| LID_T '[' BROJ_T ']'      {
    if (liste.find(*$1) == liste.end())
        yyerror(*$1 + " nije deklarisana lista!");
    $$ = (*liste[*$1])[$3];
    delete $1;
}
;

lista_izraz: '[' lista_vrednosti ']'        {
    $$ = $2;
}
| LID_T     {
    if (liste.find(*$1) == liste.end())
        yyerror(*$1 + " nije deklarisana lista!");
    $$ = new std::vector<int>(*liste[*$1]);
    delete $1;
}
;

lista_vrednosti: lista_vrednosti ',' izraz      {
    $$ = $1;
    $$->push_back($3);
}
| izraz     {
    $$ = new std::vector<int>();
    $$->push_back($1);
}
;

%%

int main() {

    if (yyparse() == 0) {
        std::cout << "Ispravna gramatika" << std::endl;
    } else {
        std::cout << "Neispravna gramatika" << std::endl;
    }

    exit(EXIT_SUCCESS);
}